IMAGE_NAME = "generic/ubuntu1804"
N = 2

Vagrant.configure("2") do |config|
    config.ssh.insert_key = false
    config.ssh.forward_agent = true
    config.ssh.private_key_path = File.expand_path('~/.ssh/insecure_private_key')

    config.vm.provider "hyperv" do |h|
        h.linked_clone = true
        h.maxmemory = 4096
        h.memory = 4096
        h.cpus = 2
    end
  
    config.vm.define "k8s-master" do |master|
        master.vm.box = IMAGE_NAME
        master.vm.network "private_network", ip: "192.168.50.10"
        master.vm.hostname = "k8s-master"
        master.vm.provision  "docker", type:'ansible' do |ansible|
            ansible.config_file = 'ansible.cfg'
            ansible.playbook = 'docker/docker-playbook.yml'
            ansible.host_key_checking = false
        end
        master.vm.provision  "preflight", type:'ansible' do |ansible|
            ansible.config_file = 'ansible.cfg'
            ansible.playbook = 'k8s/preflight-playbook.yml'
            ansible.host_key_checking = false
        end
        master.vm.provision  "master", type:'ansible' do |ansible|
            ansible.config_file = 'ansible.cfg'
            ansible.playbook = 'k8s/master-playbook.yml'
            ansible.host_key_checking = false
            ansible.extra_vars = {
                ansible_user: "vagrant"
            }
        end
    end

    (1..N).each do |i|
        config.vm.define "node-#{i}" do |node|
            node.vm.box = IMAGE_NAME
            node.vm.network "private_network", ip: "192.168.50.#{i + 10}"
            node.vm.hostname = "node-#{i}"
            node.vm.provision  "docker", type:'ansible' do |ansible|
                ansible.config_file = 'ansible.cfg'
                ansible.playbook = 'docker/docker-playbook.yml'
                ansible.host_key_checking = false
            end
            node.vm.provision  "preflight", type:'ansible' do |ansible|
                ansible.config_file = 'ansible.cfg'
                ansible.playbook = 'k8s/preflight-playbook.yml'
                ansible.host_key_checking = false
            end
            node.vm.provision  "node", type:'ansible' do |ansible|
                ansible.config_file = 'ansible.cfg'
                ansible.playbook = 'k8s/node-playbook.yml'
                ansible.host_key_checking = false
            end
        end
    end
end