---
- hosts: masters
  become: true
  tasks:
    - name: Check if Kubernetes admin was already initialized
      find:
        paths: /etc/kubernetes/manifests/
      register: files_found

    - name: Initialize the Kubernetes cluster using kubeadm
      command: kubeadm init --apiserver-advertise-address="{{ ansible_eth0.ipv4.address }}" --apiserver-cert-extra-sans="{{ ansible_eth0.ipv4.address }}"  --node-name k8s-master --pod-network-cidr=10.244.0.0/16
      when: files_found.matched == 0
      register: kubeadm

    - name: Setup kubeconfig for ubuntu user
      command: "{{ item }}"
      with_items:
        - mkdir -p /home/ubuntu/.kube
        - cp /etc/kubernetes/admin.conf /home/ubuntu/.kube/config
        - chown ubuntu:ubuntu /home/ubuntu/.kube/config
      when: kubeadm.changed

    - name: Install flannel pod network
      become: false
      command: kubectl create -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml
      when: kubeadm.changed
      
    - name: Generate join command
      command: kubeadm token create --print-join-command
      register: join_command

    - name: Copy join command to local file
      local_action: copy content="{{ join_command.stdout_lines[0] }}" dest="./join-command"
