---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: rabbitmq-data-0
  labels:
    type: local
spec:
  storageClassName: standard
  capacity:
    storage: 12Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: rabbitmq-data-1
  labels:
    type: local
spec:
  storageClassName: standard
  capacity:
    storage: 12Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"