---
kind: Service
apiVersion: v1
metadata:
  namespace: default
  name: rabbitmq-client
  labels:
    app: rabbitmq
    type: NodePort
spec:
  type: NodePort
  ports:
    - name: http
      protocol: TCP
      port: 15672
    - name: amqp
      protocol: TCP
      port: 5672
    - name: mqtt
      protocol: TCP
      port: 1883
  selector:
    app: rabbitmq
  externalIPs:
    - 3.236.54.101
