---
apiVersion: v1
kind: ConfigMap
metadata:
  name: rabbitmq-config
  namespace: test-rabbitmq
data:
  enabled_plugins: |
    [rabbitmq_peer_discovery_k8s, rabbitmq_management, rabbitmq_mqtt].
  rabbitmq.conf: |
    cluster_formation.peer_discovery_backend = k8s
    cluster_formation.k8s.host = kubernetes.default.svc.cluster.local
    cluster_formation.k8s.address_type = hostname
    cluster_formation.k8s.service_name = rabbitmq-headless
    queue_master_locator=min-masters
    mqtt.listeners.tcp.default = 1883
    mqtt.allow_anonymous  = true
    mqtt.default_user     = guest
    mqtt.default_pass     = guest
    mqtt.vhost            = /
    mqtt.exchange         = amq.topic
    mqtt.subscription_ttl = 86400000
    mqtt.prefetch         = 10
