apiVersion: v1
kind: PersistentVolume
metadata:
  name: rabbitmq-data
  namespace: test-rabbitmq
  labels:
    type: local
spec:
  storageClassName: standard
  capacity:
    storage: 12Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/pv_data"
