---
- name: Check if Kubernetes admin was already initialized
  find:
    paths: /etc/kubernetes/manifests/
  register: files_found

- name: Initialize the Kubernetes cluster using kubeadm
  command: kubeadm init --apiserver-advertise-address="{{ ansible_default_ipv4.address }}" --apiserver-cert-extra-sans="{{ ansible_default_ipv4.address }}"  --node-name k8s-master --pod-network-cidr=10.244.0.0/16
  when: files_found.matched == 0
  register: kubeadm

- name: Check if Kubernetes user was already configured
  stat:
    path: /home/{{ ansible_user }}/.kube
  register: check_file

- name: Setup kubeconfig for ubuntu user
  command: "{{ item }}"
  with_items:
    - mkdir -p /home/{{ ansible_user }}/.kube
    - cp /etc/kubernetes/admin.conf /home/{{ ansible_user }}/.kube/config
    - chown {{ ansible_user }}:{{ ansible_user }} /home/{{ ansible_user }}/.kube/config
  when: check_file.stat.exists == False

- name: Install flannel pod network
  become: false
  command: kubectl create -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml
  when: check_file.stat.exists == False

- name: Generate join command
  command: kubeadm token create --print-join-command
  register: join_command

- name: Copy join command to local file
  become: false
  local_action: copy content="{{ join_command.stdout_lines[0] }}" dest="join-command"
