---
- name: Install packages that allow apt to be used over HTTPS
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
  when:
    - ansible_distribution == 'Ubuntu'

- name: Install docker prerequisites on CentOS
  yum:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
      - yum-utils
      - device-mapper-persistent-data
      - lvm2
  when:
    - ansible_distribution == 'CentOS'

- name: Add an apt signing key for Docker on Ubuntu
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  when:
    - ansible_distribution == 'Ubuntu'

- name: Add an apt signing key for Docker on Raspbian
  apt_key:
    url: https://download.docker.com/linux/raspbian/gpg
    state: present
  when:
    - ansible_distribution == 'Debian'
    - ( ansible_facts.architecture is search("arm") and
      ansible_facts.userspace_bits == "64" ) or
      ansible_facts.architecture is search("aarch64")

- name: Add apt repository for stable Ubuntu version on Architecture x86_64
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable
    state: present
  when:
    - ansible_facts.architecture == "x86_64"
    - ansible_distribution == 'Ubuntu'

- name: Add apt repository for stable Raspbian
  apt_repository:
    repo: deb [arch=arm64] https://download.docker.com/linux/raspbian buster stable
    state: present
  when:
    - ansible_distribution == 'Debian'
    - ( ansible_facts.architecture is search("arm") and
      ansible_facts.userspace_bits == "64" ) or
      ansible_facts.architecture is search("aarch64")

- name: Add apt repository for stable Ubuntu version on Architecture arm64
  apt_repository:
    repo: deb [arch=arm64] https://download.docker.com/linux/ubuntu bionic stable
    state: present
  when:
    - ( ansible_facts.architecture is search("arm") and
      ansible_facts.userspace_bits == "64" ) or
      ansible_facts.architecture is search("aarch64")

- name: Add Docker repository on CentOS
  get_url:
    url: https://download.docker.com/linux/centos/docker-ce.repo
    dest: /etc/yum.repos.d/docker-ce.repo
  when:
    - ansible_distribution == 'CentOS'

- name: Install docker and its dependecies on APT based Systems
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
      - docker-ce
      - docker-ce-cli
      - containerd.io
  notify:
    - docker status
  when:
    - (ansible_distribution == 'Ubuntu' or ansible_distribution == 'Debian')

- name: Install docker and its dependecies on YUM based Systems
  yum:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
      - docker-ce
      - docker-ce-cli
      - containerd.io
  notify:
    - docker status
  when:
    - (ansible_distribution == 'CentOS')

- name: Add {{ ansible_user }} user to docker group
  user:
    name: "{{ ansible_user }}"
    group: docker

- name: Start and Enable Docker
  systemd:
    name: docker
    state: started
    enabled: yes
    daemon-reload: yes
