---
k3s_version: v1.17.5+k3s1
ansible_user: ubuntu
ansible_ssh_private_key_file: /home/alessandrocb/.ssh/AWS/teste.pem
systemd_dir: /etc/systemd/system
master_ip: "{{ hostvars[groups['master'][0]]['ansible_host'] | default(groups['master'][0]) }}"
extra_server_args: ""
extra_agent_args: ""
